export const ADD_FOOD = 'ADD_FOOD';
export const EDIT_FOOD = 'EDIT_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const LOADED_FOOD = 'LOADED_FOOD';
export const FAIL_LOADED_FOOD = 'FAIL_LOADED_FOOD';
export const BEGIN_ADD_NEW_FOOD = 'BEGIN_ADD_NEW_FOOD';
export const CANCEL_ADD_NEW_FOOD = 'CANCEL_ADD_NEW_FOOD';

export const LOADED_EATING_TYPE_DICT = 'LOADED_EATING_TYPE_DICT';
export const LOADED_FOOD_TYPE_DICT = 'LOADED_FOOD_TYPE_DICT';
export const FIAL_LOADED_EATING_TYPE_DICT = 'FIAL_LOADED_EATING_TYPE_DICT';
export const FIAL_LOADED_FOOD_TYPE_DICT = 'FIAL_LOADED_FOOD_TYPE_DICT';
export const ADD_EATING_TYPE = 'ADD_EATING_TYPE';
export const ADD_FOOD_TYPE = 'ADD_FOOD_TYPE';

export const DICT_ADDING_BEGIN = 'DICT_ADDING_BEGIN';
export const DICT_ADDING_CANCEL = 'DICT_ADDING_CANCEL';